name: Java App Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: '17'
  DOCKER_IMAGE: 'test-java-app'
  DOCKER_TAG: 'latest'
  SEVERITY_LEVEL: 'CRITICAL,HIGH'

jobs:
  security_scan:
    name: Scan Java App Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Files in Repository
        run: ls -R   

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven
  
      - name: Verify Maven Installation
        run: mvn -version
  
      - name: Build Java Application
        run: mvn clean package -DskipTests
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} -f ./Dockerfile .

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}'
          format: 'table'
          exit-code: 1
          severity: '${{ env.SEVERITY_LEVEL }}'

      - name: Cleanup Docker Image
        run: docker rmi ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} || true
