name: Java App Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: '17'
  DOCKER_IMAGE: 'test-java-app'
  DOCKER_TAG: 'latest'
  DOCKERHUB_USERNAME: 'gsmehra01'
  DOCKERHUB_REPO: 'java-trivy'
  SEVERITY_LEVEL: 'CRITICAL,HIGH'

jobs:
  security_scan:
    name: Scan Java App Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Files in Repository
        run: ls -R   

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven
  
      - name: Verify Maven Installation
        run: mvn -version
  
      - name: Build Java Application
        run: mvn clean package -DskipTests
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      
      - name: Build Docker Image
        run: |
           docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ env.DOCKER_TAG }} .
           docker images

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}'
          format: 'table'
          exit-code: 0
          severity: '${{ env.SEVERITY_LEVEL }}'
      
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
    

      - name: Logout from Docker Hub
        run: docker logout
